# Generated by Django 2.2.19 on 2021-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome')),
                ('nome_instrutor', models.CharField(max_length=255, verbose_name='Nome do Instrutor')),
                ('exercicios', models.CharField(max_length=400, verbose_name='Exercicios')),
                ('tipo_treino', models.CharField(max_length=64, verbose_name='Tipo de Treino')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
            ],
        ),
    ]
