# Generated by Django 2.2.19 on 2021-04-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='nome_instrutor',
        ),
        migrations.AddField(
            model_name='ficha',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.Cliente'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.Funcionario'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='objetivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Objetivo do Cliente'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_instrutor',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='exercicios',
            field=models.CharField(max_length=255, verbose_name='Exercicios'),
        ),
    ]
