# Generated by Django 2.2.19 on 2021-06-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20210608_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='fichas',
        ),
        migrations.AddField(
            model_name='ficha',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='academia.Funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academia.Cliente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='exercicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academia.Exercicio'),
        ),
    ]
