# Generated by Django 2.2.19 on 2021-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_auto_20210608_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='exercicios',
        ),
        migrations.AddField(
            model_name='ficha',
            name='exercicios',
            field=models.ManyToManyField(to='academia.Exercicio'),
        ),
    ]
