# Generated by Django 2.2.19 on 2021-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_auto_20210608_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Ficha'),
        ),
    ]
