# Generated by Django 2.2.19 on 2021-06-10 19:11

import academia.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_ficha_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=academia.models.get_file_path, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=academia.models.get_file_path, verbose_name='Foto'),
        ),
    ]
