# Generated by Django 2.2.19 on 2021-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_auto_20210610_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
    ]
